apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kataconfigs.kataconfiguration.openshift.io
spec:
  group: kataconfiguration.openshift.io
  names:
    kind: KataConfig
    listKind: KataConfigList
    plural: kataconfigs
    singular: kataconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KataConfig is the Schema for the kataconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KataConfigSpec defines the desired state of KataConfig
          properties:
            kataImage:
              description: KataImage blah blah blah blah blah blah
              type: string
            runtimeClass:
              description: RuntimeClass blah blah
              type: string
          required:
          - kataImage
          - runtimeClass
          type: object
        status:
          description: KataConfigStatus defines the observed state of KataConfig
          properties:
            completedNodesCount:
              type: integer
            failedNodes:
              items:
                description: FailedNode abc
                properties:
                  error:
                    type: string
                  name:
                    type: string
                required:
                - error
                - name
                type: object
              type: array
            inProgressNodesCount:
              type: integer
            totalNodesCount:
              type: integer
          required:
          - completedNodesCount
          - failedNodes
          - inProgressNodesCount
          - totalNodesCount
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
